### ISSUE TITLE
createIndex issue

### ISSUE THREAD

**Issue by danielsss** [winstonjs/winston-mongodb#100]
The winston-mongodb will automatically create an expire Index and key as -1. it will invoke an Error when i've created this index with key as 1.
`error: [Line: 191] [File: client.js] creating logger index: MongoError: exception: Trying to create an index with same name timestamp_1 with different key spec { timestamp: 1 } vs existing spec { timestamp: -1 } at Function.MongoError.create (/opt/cms/20170525170415/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11) at /opt/cms/20170525170415/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:754:66 at Callbacks.emit (/opt/cms/20170525170415/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3) at Connection.messageHandler (/opt/cms/20170525170415/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23) at Socket.<anonymous> (/opt/cms/20170525170415/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:547:20)`

Would you change this strategy ?

**Comment by yurijmikhalevich** [comment]
Hi. Which `winston-mongodb` version are using?

**Comment by danielsss** [comment]
@yurijmikhalevich Sorry, It has been for long, and I can't remember that.
