### ISSUE TITLE
A connection warning

### ISSUE THREAD

**Issue by maicss** [winstonjs/winston-mongodb#103]
```
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. 
Please authenticate using MongoClient.connect with auth credentials.
```

**Comment by yurijmikhalevich** [comment]
Thank you for bringing this up.
Removed support of obsolete `options.username` and `options.password` from winston-mongodb@3.0.0.
You are now expect to pass `username:password` in the Mongo URI or perform authentication by yourself and pass pre-connected db object to the transport.
