### ISSUE TITLE
meta data not stored in mongo

### ISSUE THREAD

**Issue by alisherafat** [winstonjs/winston-mongodb#104]
I have custom classes for errors with properties like statusCode,serverResponse (int or string) but only in meta attribute of each document,  three options (message,name and stack) exists and other options are not stored!
Error object passed to winston logger:
`{
  "message": "Not found!",
  "stack": "stack trace ....." ,
  "name": "NotFoundError",
  "status": 404,
  "path": "http://localhost:3000/sddfasdf",
  "level": "error",
  "timestamp": "2017-09-14 04:34:55"
}`

mongo transport config:  

`
const errorLoggerTransports = [
    new (winston.transports.MongoDB)({
        db: config.uri,
        collection: 'error_logs',
        handleExceptions: true,
        capped: true,
    })];
`

**Comment by yurijmikhalevich** [comment]
Thank you. Fixed. To be released in v3.0.1.

**Comment by alisherafat01** [comment]
![image](https://user-images.githubusercontent.com/13902663/45583645-59476580-b8db-11e8-8d33-9c4720195679.png)
Is it possible to set "key" property beside timestamp(in root object) instead of in meta object?

**Comment by mrunderline** [comment]
i have the same issue in v5.0.0 of winston-mongodb and v3.4.0 of express-winston.
how can i fix it?
