### ISSUE TITLE
Date turns into empty object

### ISSUE THREAD

**Issue by huhamhire** [winstonjs/winston-mongodb#105]
I have tried to store `Date` object as meta attribute into mongodb, something like: 
```javascript
{
    expire_time: new Date()
}
```
But it became an empty object: 
```javascript
{
    expire_time: {
         
    }
}
```
The `makeObjectNonCircular` method treat Date object as an object.

winston-mongodb version: 2.0.10

**Comment by yurijmikhalevich** [comment]
Thank you. Fixed. To be released in version 3.0.1.
