### ISSUE TITLE
Is it still possible to avoid meta field?

### ISSUE THREAD

**Issue by adriano-di-giovanni** [winstonjs/winston-mongodb#107]
I'm upgrading from old versions of winston and winston-mongodb. I can't get my JSON data at root level in the MongoDB document that's logged by winston. I always get the meta field only. Is it still possible to have the legacy behavior?

**Comment by yurijmikhalevich** [comment]
No.
We switched to the `meta` field because original approach could lead to log object inconsistency and therefore was unsafe.
