### ISSUE TITLE
[Error] common.clone is not a function

### ISSUE THREAD

**Issue by khayalan-mathew** [winstonjs/winston-mongodb#108]
I'm trying to use this module with the current winston@3.0.0 version.
but everytime it tries to log something into the mongodb the following error occures
```
F:\Coding\skillar\node_modules\winston-mongodb\lib\helpers.js:22
  meta = common.clone(meta);
                ^

TypeError: common.clone is not a function
    at Object.exports.prepareMetaData.meta [as prepareMetaData] (F:\Coding\skillar\node_modules\winston-mongodb\lib\helpers.js:22
:17)
    at process.nextTick (F:\Coding\skillar\node_modules\winston-mongodb\lib\winston-mongodb.js:191:26)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
I can't help myself because i dont know, what the reason for the error is.

**Comment by sandscap-sc** [comment]
It looks like winston-mongodb is not compatible with winston v3. Use latest 2.x for now.

**Comment by yurijmikhalevich** [comment]
@khayalan-mathew thanks for reporting. Will look into it.
@sandscap-sc you are right, thanks for pointing out.

**Comment by mdewey** [comment]
@yurijmikhalevich has there been any progress on this? I ran into this issue of wanting to use winston v3, not v2.X. I can work on this if you aren't currently working on it

**Comment by yurijmikhalevich** [comment]
@mdewey @khayalan-mathew initial winston3 support was added in winston-mongodb@4.0.0-rc0, latest version is winston-mongodb@4.0.0-rc1.
This issue will be closed after complete support will be released.

**Comment by Jeff-Lewis** [comment]
@yurijmikhalevich did you mean winston 3 support was added in [winston-mongodb v3.0.1](https://github.com/winstonjs/winston-mongodb/releases/tag/v3.0.1)? 

The only `rc` releases I see are [3.0.0-rc0](https://github.com/winstonjs/winston/releases/tag/3.0.0-rc0) and [3.0.0-rc1](https://github.com/winstonjs/winston/releases/tag/3.0.0-rc1) in the main [winston](https://github.com/winstonjs/winston/releases) module.

**Comment by yurijmikhalevich** [comment]
@Jeff-Lewis Can you please, try again:
``` ~ npm info winston-mongodb version 
4.0.0-rc1```

**Comment by Jeff-Lewis** [comment]
@yurijmikhalevich Thanks, I see it now and its [branch](https://github.com/winstonjs/winston-mongodb/tree/winston3-support).

**Comment by yurijmikhalevich** [comment]
Winston 3 and mongodb 3 support is now in the winston-mongodb 4.x branch.
