### ISSUE TITLE
How to set the "meta" property

### ISSUE THREAD

**Issue by gustavomassa** [winstonjs/winston-mongodb#116]
Hello,

I would like to know how I can set the meta property. Also how I can format/override the timestamp property, it is not getting the correct timezone.

Thank you!

**Comment by Yaxian** [comment]
@gustavomassa 

```js
import winston from 'winston';
import 'winston-mongodb';
const logger = winston.createLogger({
  exitOnError: false, // By default, winston will exit after logging an uncaughtException
  transports: [
    new winston.transports.MongoDB({
      level: 'info',
      db: `mongodb://localhost:27107/winston-logs`,
      collection: 'forge-rcdb'
    })
  ]
});

// logger[LEVEL](message, meta)
logger.info('msg', { metaKey:  'metaValue' })

or 

logger.log({
  level: 'info',
  message: 'it is a message',
  meta: {}
})

```

**Comment by yurijmikhalevich** [comment]
@Yaxian thank you!

@gustavomassa see the comment above, please.

For the timezone, I suggest you fix timezone at your server.

**Comment by claudiut** [comment]
@Yaxian, this is not working: `logger.info('msg', { metaKey:  'metaValue' })`, this is working:
```js
logger.info('msg', {meta: { metaKey:  'metaValue' }})
```
;)

**Comment by soumyakantiroychowdhury** [comment]
> @Yaxian, this is not working: `logger.info('msg', { metaKey: 'metaValue' })`, this is working:
> 
> ```js
> logger.info('msg', { meta: { metaKey:  'metaValue' } })
> ```
> 
> ;)

`logger.info('msg', { metaKey: 'metaValue' })` => Works in version 5.0.1
`logger.info('msg', { meta: { metaKey:  'metaValue' } })` => Works in version 4.0.3

Transport option `metaKey` was added after version 4.0.3 (I am not sure exactly which version). I observed the difference in usage in the above mentioned versions.

I am although not happy with the implementation. My expectation was if I set `metaKey` to `mykey`, the document should have `{..., mykey: myvalue}`, instead I see `{..., meta: myvalue}` in the document stored in MongoDB.

**Comment by lucyaraujo21** [comment]
logger.info('msg', { metadata: { 'metaKey' : 'metaValue' } }) => Works in version 5.0.5

I use this implementation with MongoDB. It allowed me to save a set { 'metaKey' : 'metaValue , 'metaKey' : 'metaValue' } in the document stored in MongoDB
