### ISSUE TITLE
Error:  UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: cb is not a function

### ISSUE THREAD

**Issue by cdcv** [winstonjs/winston-mongodb#117]
Attempting to use winston-mongodb in a meteor app.
See code below.
Get two server errors:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: cb is not a function
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The server throws the first error for each new log entry.
Looking in the database, a new collection is created, and entries are made, but they look like this (no contents):

{ 
    "_id" : ObjectId("5a6152a441e015a523afe497"), 
    "timestamp" : ISODate("2018-01-18T19:06:28.047-0700"), 
    "level" : null, 
    "message" : "undefined", 
    "meta" : null
}
Thanks for the help.

Code:
winston = require('winston');
require('winston-loggly-bulk');
require('winston-mongodb'); // meteor npm install --save winston-mongodb, send log to mongo database

var logit = false;
AppLogMongoDBOptions = {
    db: process.env.MONGO_URL,
    collection: 'AppLogger',
    name:'mongo.mainLogs'
};

// logging levels
const winstonLevels = {
    emerg: 0,
    alert: 1,
    crit: 2,
    error: 3,
    warning: 4,
    notice: 5,
    info: 6,
    debug: 7
}
winston.setLevels(winstonLevels);

//Loggly transport
winston.add(winston.transports.Loggly, Meteor.settings.AppLogger);

// MongoDB Transport
winston.add(winston.transports.MongoDB, AppLogMongoDBOptions);

**Comment by JoHuang** [comment]
the same issue here

**Comment by yurijmikhalevich** [comment]
@cdcv can you please check whether updating to mongodb 3.x, winston 3.x and winston-mongodb 4.x solved your issue?
