### ISSUE TITLE
Currect usage?

### ISSUE THREAD

**Issue by RedHatter** [winstonjs/winston-mongodb#119]
I think I'm missing something.

    let logger = winston.createLogger({
      transports: [
        new winston.transports.MongoDB({ db })
      ]
    })

    logger.log({
      level: 'info',
      message: 'it is a message',
      data: 'some data'
    })

The code above produces the following mongo object.

    {
      "_id": ObjectId("5aa6d2a36d9a9444baccb777"),
      "timestamp": ISODate("2018-03-12T19:18:59.964Z"),
      "level": "info",
      "message": "{\"level\":\"info\",\"message\":\"it is a message\",\"data\":\"some data\"}",
      "meta": null
    }

I would have expected something like this.

    {
      "_id": ObjectId("5aa6d2a36d9a9444baccb777"),
      "timestamp": ISODate("2018-03-12T19:18:59.964Z"),
      "level": "info",
      "message": "it is a message",
      "data": "some data"
    }

What is the suggested usage?

**Comment by Leland-Kwong** [comment]
I ran into this same issue. I'm currently using this setup which sets all the data onto the `meta` property.

``` javascript
const { format, createLogger, transports } = require('winston');
require('winston-mongodb');
const logger = new createLogger({
  format: format.printf((info) => 
    info.message
  ),
  transports: [
    new transports.MongoDB({
      db: getDb(),
      collection: 'logs',
    })
  ]
});

logger.log({
  level: 'info',
  message: 'my message',
  meta: {
    myProp: 'foo'
  }
});
/* MongoDB document
{
  "_id" : ObjectId("5ab3fb3989ce7a0fe0aa4ff3"),
  "timestamp" : ISODate("2018-03-22T18:51:37.937Z"),
  "level" : "info",
  "message" : "my message",
  "meta" : {
      "myProp" : "foo",
  }
}
*/
```

**Comment by yurijmikhalevich** [comment]
@RedHatter fixed in v4.0.2.

**Comment by kunokdev** [comment]
This behaviour doesn't work in version 5.0.0

**Comment by Maha-Shawky** [comment]
use metadata instead of meta, or set metaKey option
https://github.com/winstonjs/winston-mongodb/blob/37ad8418b2ec6906c113b9f2ae7e651ee0f4aa0d/lib/winston-mongodb.js#L82

`.log({
        level: 'info',
        message: 'log message',
        **metadata**: {
            prop: 'xyz'
        }
    });`

**Comment by vighnesh153** [comment]
> use metadata instead of meta, or set metaKey option
> https://github.com/winstonjs/winston-mongodb/blob/37ad8418b2ec6906c113b9f2ae7e651ee0f4aa0d/lib/winston-mongodb.js#L82
> 
> `logger.log({ level: 'info', message: 'log message', metadata: { prop: 'xyz' } });`

This is a good solution. But in my case, I already had an entire app built with logging. To show all the data in the MongoDB logs, I didn't want to changes logging at all places. So, I used the Proxy class to do that for me.

```js
const loggerProxy = new Proxy(logger, {
  get(target, prop) {
    return (logObject = {}) => {
      const logData = {};
      if (`${logObject}` === logObject) {   // if logging string
        logData.message = logObject;
      } else {
        logData.message = logObject.message;
        delete logObject.message;
        logData.metadata = logObject;
      }

      logger[prop](logData);
    };
  },
});
```
