### ISSUE TITLE
winston.transports.MongoDB is not a constructor

### ISSUE THREAD

**Issue by somppa** [winstonjs/winston-mongodb#120]
Error appears after updating winston 2.4.0 -> 2.4.1.

```
let logger = new winston.Logger({
  level: "info",
  transports: [
    new winston.transports.MongoDB({
      db: 'mongodb://localhost:27017/logger',
      collection: 'logs',
      storeHost: true
    })
  ]
});
```

Results to
`TypeError: winston.transports.MongoDB is not a constructor`

Downgrading back to 2.4.0 fixes this issue as a temporary solution

**Comment by Leland-Kwong** [comment]
Try upgrading to latest `3.0.0` release. I'm using it right now and it works.

**Comment by yurijmikhalevich** [comment]
@somppa @Leland-Kwong please, consider upgrading to winston 3.x, mongodb 3.x and winstong-mongodb 4.x.
