### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by pawelotto** [winstonjs/winston-mongodb#123]
```
winston-mongodb, initialization error:  TypeError: Cannot read property 'indexInformation' of undefined
    at db.createCollection.then.col (/<mymodule>/node_modules/winston-mongodb/lib/winston-mongodb.js:106:18)
```

**Comment by alisherafat01** [comment]
same problem for me!  any solution?
code:
`new winston.transports.MongoDB({
      db: mongoose.connection
    }),`

**Comment by yurijmikhalevich** [comment]
@pawelotto @alisherafat01 please, consider upgrading to the winston-mongodb 4.x, winston 3.x and mongodb 3.x.

It tested to work here: https://github.com/winstonjs/winston-mongodb/blob/master/test/winston-mongodb-test.js#L25
