### ISSUE TITLE
db.createCollection is not a function

### ISSUE THREAD

**Issue by RedHatter** [winstonjs/winston-mongodb#126]
I can't get this transport to work. The simple example below throw 'TypeError: db.createCollection is not a function'.

    const winston = require('winston')
    const { MongoClient } = require('mongodb')
    require('winston-mongodb')

    let db = MongoClient.connect('mongodb://localhost:27017/prompt')

    const logger = winston.createLogger({
      level: process.env.LOG_LEVEL || 'info',
      format: winston.format.printf(info => info.message),
      transports: [
        new winston.transports.MongoDB({ db })
      ]
    })

In my `package.json`

    "mongodb": "^3.0.7",
    "winston": "^3.0.0-rc5",
    "winston-mongodb": "^4.0.0-rc1"

**Comment by abstractk** [comment]
+1

**Comment by yurijmikhalevich** [comment]
@RedHatter, @abstractk fixed. Released as v4.0.0.
