### ISSUE TITLE
is this package still maintained?

### ISSUE THREAD

**Issue by MastroLindus** [winstonjs/winston-mongodb#127]
Just wondering if this package is still maintained as I have a few issues making it run:
1)Can you provide an example on how to properly use it with typescript? Whatever I do I still get the error that "MongoDB" doesn't exist on the "transports" object. 
2)Even by ignoring the typescript compiler, when I run my app I see a warning about this being an old legacy transport, and that should be updated to winston@3 syntax.
3)As a side note, the package.json still declares that this package depends on @types/winston when the current winston stable ships with its own typings in the library itself, and the one @types are outdated.

I tried to use both the winston-mongodb@3.0.2 and @4.0.0.rc1
The transport looks promising and very useful, it would be a pity if it was not compatible anymore with the current winston release and typings..

**Comment by yurijmikhalevich** [comment]
Thank you guys! Will close the issues soon.
