### ISSUE TITLE
Broken typescript definition?

### ISSUE THREAD

**Issue by xduseko** [winstonjs/winston-mongodb#131]
Hi,

I'm trying to use winston-mongodb@3.0.1 because it's the last version compatible with winston@2.x, right? Version 3.x is not stable yet, it contains major bugs like (e.g. winstonjs/winston#1426). Anyway problem is that typing seems to be somehow wrong.
&nbsp;

```
import {MongoDB} from "winston-mongodb";
```
TS2305: module has no exported member 'MongoDB'
&nbsp;

```
import {transports} from "winston";
import "winston-mongodb";

new transports.MongoDB({});
```
TS2339: Property 'MongoDB' does not exists on type 'Transports'
&nbsp;

```
import {transports} from "winston-mongodb";
new transports.MongoDB({});
```
TypeError: Cannot read property 'MongoDB' of undefined
&nbsp;

How can I properly instantiate MongoDB transport in typescript? An example would be appreciated. Thanks!

**Comment by yurijmikhalevich** [comment]
Hi @xduseko.

Version 3.0.2 is the latest version supporting winston@2.x and has fixed TypeScript definitions.

**Comment by xduseko** [comment]
Oh thanks, I haven't seen that in release list at https://github.com/winstonjs/winston-mongodb/releases.

**Comment by yurijmikhalevich** [comment]
@xduseko oops. We do miss this in a `releases` pane. Thank you!

The best way to check available versions is: `npm info <module-name> versions`.
