### ISSUE TITLE
couple of issues in 4.0.3.

### ISSUE THREAD

**Issue by MastroLindus** [winstonjs/winston-mongodb#137]
First: after updating I see this message in the console that I didn't see before (downgrading to 3.0.2. fixes it, but since I am using winston 3 I have other deprecation errors so I want to stick with 4)

"exists is not a function"
the call to exists is definitely not in my codebase

Also, there are a couple of closed issues about typescript typings and it is mentioned that they are fixed in 3.0.2, but are they supposed to be fixed also in 4.0.3? Doing this in this version still gives me the error that transports don't have mongoDb defined:

import { createLogger, format, transports, Logger } from "winston";
require("winston-mongodb");

new transports.MongoDB({ options})     <- MongoDB is not defined

**Comment by ivanTemelkov** [comment]
Opps, I found a typo:
It's 
`new winston.transports.MongoDB({`
and not
`new winston.transports.MongoDb({`

> 
> 
> I have the same issue.
> With winston 3.1.0 and winston-mongodb 4.0.3
> winston.transports.MongoDb is not defined:
> 
> ```
> const winston = require('winston');
> require('winston-mongodb');
> 
> const logger = winston.createLogger({
>         level: 'info',
>         format: winston.format.json(),
>         transports: [
>             new winston.transports.File({ filename: 'logfile.log' }),
>             new winston.transports.MongoDb({
>                 db: <connectionString>,
>                 options: {
>                     useNewUrlParser: true,
>                   }
>             })
>         ]
>     });
> ```

**Comment by MastroLindus** [comment]
@ivanTemelkov are you talking about runtime or compileTime(typescript) ? 
Because my code at runtime is completely fine, it's only the typescript typing not working (the type for winston.transports doesn't contain MongoDB)

**Comment by ivanTemelkov** [comment]
Thank you for your reply!
As I wrote earlier I have found a typo in my code.
Greatings!

> 
> 
> @ivanTemelkov are you talking about runtime or compileTime(typescript) ?
> Because my code at runtime is completely fine, it's only the typescript typing not working (the type for winston.transports doesn't contain MongoDB).
> 
> So far I flag it with @ts-ignore to avoid the compiler error, but it's not an ideal long-term solution...

**Comment by yurijmikhalevich** [comment]
Typings issue were fixed in v4 branch, please update winston-mongodb to the latest version.
