### ISSUE TITLE
Link on project homepage seems obsolete: indexzero

### ISSUE THREAD

**Issue by rap2hpoutre** [winstonjs/winston-mongodb#141]
http://github.com/indexzero/winston-mongodb may be replaced by https://github.com/winstonjs/winston-mongodb

**Comment by yurijmikhalevich** [comment]
@indexzero can you please change this or give me rights to edit the repo description?

**Comment by DABH** [comment]
Where is the bad link?  In the Winston readme?  I can fix it, or open a PR and I’ll merge it - just let me know

**Comment by yurijmikhalevich** [comment]
![image](https://user-images.githubusercontent.com/4187729/54748045-17d5a100-4c03-11e9-89ec-bfac27fcdd97.png)

@DABH here ^

**Comment by DABH** [comment]
Oh, lol, yeah @indexzero does need to fix that, I don't have admin access on -mongodb (only on the core winston repos).  Sorry about that! : (  (@indexzero , alternatively, feel free to grant me permissions on this repo, ha)

**Comment by DABH** [comment]
(Separately -- thank you @yurijmikhalevich for all your work on this repo recently, it's greatly appreciated!!)

**Comment by yurijmikhalevich** [comment]
@DABH thank you! :-) 
It's my pleasure.

**Comment by indexzero** [comment]
Done and done. Sorry it took so long folks

**Comment by yurijmikhalevich** [comment]
@indexzero thank you!
