### ISSUE TITLE
DeprecationWarning: current URL string parser is deprecated

### ISSUE THREAD

**Issue by handu** [winstonjs/winston-mongodb#146]
Using "winston": "^3.1.0" and "winston-mongodb": "^4.0.3", I get deprecation warning:
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

Adding
```
logger.options.useNewUrlParser = true;
```
at the top of the connectToDatabase(logger) solves the problem.
```
function connectToDatabase(logger) {
    logger.options.useNewUrlParser = true;
    return mongodb.MongoClient.connect(logger.db, logger.options
    ).then(client=>setupDatabaseAndEmptyQueue(client.db()), err=>{
      console.error('winston-mongodb: error initialising logger', err);
      if (options.tryReconnect) {
        console.log('winston-mongodb: will try reconnecting in 10 seconds');
        return new Promise(resolve=>setTimeout(resolve, 10000)
        ).then(()=>connectToDatabase(logger));
      }
    });
  }
```

**Comment by YellowFish085** [comment]
Without changing the library code, you have an optional parameter named `options` described as follow in the README:

> - **options**: MongoDB connection parameters (optional, defaults to `{poolSize: 2, autoReconnect: true}`).

So you can simply pass in this `options` parameter `useNewUrlParser: true` since the content of `options` will be used by the MongoClient ([see this line](https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L122)).

Something like:

```js
let options = {
    db: 'url',
    // ... other parameters ...
    options: {
        poolSize: 2,            // Providing an `options` parameter will
        autoReconnect: true     // override the default ones
        useNewUrlParser: true
    }
};
```

**Comment by vinaybedre** [comment]
@handu did the issue solved for you? I am facing the same problem

**Comment by mpatelatIBM** [comment]
@YellowFish085 thanks. It fixed "DeprecationWarning: current URL string parser is deprecated" issue.
