### ISSUE TITLE
Connect to MongoDB with authentication database

### ISSUE THREAD

**Issue by dhananjayaus** [winstonjs/winston-mongodb#148]
Hi Everyone,
I am new to BI connector, i am trying to connect mongoDB using mongosqld command.
Unable to connect to mongoDB using --mongo-uri , getting message as "--mongo-uri may not contain any authentication information"

Command that i tried is : mongosqld  "mongodb://username:password@host/dataDB?authSource=customAuthDB"

please suggest me on this.

Thanks,
Dhananjaya

**Comment by yurijmikhalevich** [comment]
@dhananjayaus this repo is not related to the bi connector. Please, ask your question here https://github.com/mongodb/docs-bi-connector/
