### ISSUE TITLE
Meta data is empty when using other method overload  of log

### ISSUE THREAD

**Issue by iamrommel** [winstonjs/winston-mongodb#150]
this will work, `the logger.info({message: 'i was a message', meta: { name: 'db' }})`

but winston has other overload of the method info with just two parameters
`logger.info('i was a message', {name: 'db' })`
which does not work on winston-mongodb. The message are being copied to the mongodb but the meta is null. 

I think winston-mongodb should follow the interface provided by winston

**Comment by iamrommel** [comment]
Ah i nevermind, after digging to the code it should be like this 

`logger.info('msg', { meta: { metaKey:  'metaValue' } })`

but still, it think my fingers are lazy and hate to type meta

 :)

**Comment by KeithGillette** [comment]
I was wondering why `meta` was always `null` in the MongoDB log entries even though we were passing an object argument into the `meta` parameter! This looks like it may be an inconsistency in the `winston` handling of its arguments in the method overloads: When passed as a separate object argument, `winston` appears to flatten the `meta` argument object properties into separate properties on the `TransformableInfo`  object that also contains the standard logging fields (`level`, `message`), which is then passed to the logger `format` function. However, when passed as a `meta` property inside a single `entry` object argument, the `meta` properties are _not_ flattened and instead all appear in an intact object on a single `meta` property of the `TransformableInfo` object. This difference in handling appears in transports other than `winston-mongo`. (I gleaned the preceding from experimenting with `transports.Console`.)

**Comment by YegorPavlenko** [comment]
> but still, it think my fingers are lazy and hate to type meta
It's not about lazyness.
I have 2624 occurrences logger methods in my project. Many of them with meta in way described above in first message, without using meta parameter:
logger.info('i was a message', {name: 'db' })
What should I do? Refactor all that calls?

**Comment by BanderasPRO** [comment]
Encountered with same problem. Works only when metadata wrapped into meta.

**Comment by yurijmikhalevich** [comment]
Fixed. Released as `v5.0.0`.

**Comment by GuillaumeRochat** [comment]
Right now (5.0.0), if we add `defaultMeta` on the logger, it just isn't displayed in the meta key in MongoDB. It is however displayed correctly if we use the default Console transport with the default cli format.

Shouldn't this line [1] be something like
```js
// Maybe there are more things to omit like `Symbol.for('level'), etc.
// Using lodash omit function for clarity purpose.
entry.meta = helpers.prepareMetaData(_.omit(info, ['level', 'message', 'splat']));
```
so we get every key in the info that are not the level, splat or message? That's the behavior I was expecting to see.

[1] https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L214

**Comment by lonix1** [comment]
I've tried every combination and I can't log the meta object. What is the correct signature?

**Comment by KeithGillette** [comment]
@lonix1 — here's what we're using:
```
import { Injectable } from 'injection-js';
import { TransformableInfo } from 'logform';
import { createLogger, format, Logger, LoggerOptions, transports } from 'winston';
import 'winston-mongodb'; // importing Winston-MongoDB extends Winston `transports` with `transports.MongoDB` property

export enum LogLevel {INFO = 'info', WARN = 'warn', ERROR = 'error'}

const metaDataKeyName = 'meta';
const defaultContextName = 'DEFAULT';

export const logTransportMongoDB = new transports['MongoDB']({
	db: process.env.MONGO_URL,
	handleExceptions: true,
	storeHost: true,
	metaKey: metaDataKeyName,
	options: {
		useNewUrlParser: true
	},
});

export const logTransportConsole = new transports.Console({
	handleExceptions: true,
	format: format.combine(
		format.timestamp(),
		format.printf((info: TransformableInfo) => {
			return `${info.timestamp} [${info[metaDataKeyName] ? info[metaDataKeyName].context : defaultContextName}] [${info.level.toLocaleUpperCase()}] ${info.message}`;
		})
	)
});

@Injectable()
export class LogService {
	private readonly logger: Logger;
	private contextName: string = defaultContextName;

	constructor() {
		this.logger = createLogger();
		this.logger.configure({
			transports: [logTransportConsole],
			exitOnError: false
		});
	}

	public configure(configuration: LoggerOptions, contextName?: string): void {
		this.logger.configure(configuration);
		this.contextName = contextName ? contextName : this.contextName;
	}

	public log(message: string): void {
		this.logger.log({level: LogLevel.INFO, message: message, meta: {context: this.contextName}});
	}

	public info(message: string): void {
		this.logger.log({level: LogLevel.INFO, message: message, meta: {context: this.contextName}});
	}

	public warn(message: string): void {
		this.logger.log({level: LogLevel.WARN, message: message, meta: {context: this.contextName}});
	}

	public error(message: string, stackTrace?: any): void {
		this.logger.log({level: LogLevel.ERROR, message: message, meta: {context: this.contextName, stackTrace: stackTrace}});
	}
}
```

**Comment by lonix1** [comment]
Strange I tried that and didn't succeed.

But this worked: `logger.info({ message, metadata: { foo: "bar" } });`

**Comment by KeithGillette** [comment]
Glad you got something to work, @lonix1. As I recall from experimenting, the metadata property name varies between the generic `log` method and the individual log-level methods.

**Comment by lonix1** [comment]
So much discrepancy between this and the main library, and these threads, the source and the readme... :laughing:

**Comment by lonix1** [comment]
@yurijmikhalevich What is the official/correct syntax?

**Comment by CassiusHorvath** [comment]
got working! Just pass meta and the error stack as an object  {meta: err}
```
function(err, req, res, next) {
  winston.error(err.message, {meta: err});
```

**Comment by TheRealJota32** [comment]
@CassiusHorvath i have the same function, but the meta property is empty, idk why, but if i pass the err like this winston.error(err.message, err); , in the console the stack is there

**Comment by jcunanan05** [comment]
> 
> 
> Thanks @KeithGillette Strange I tried that and didn't succeed.
> 
> But this worked: `logger.info({ message, metadata: { foo: "bar" } });`

not sure why `meta: {..}` not worked for me, but `metadata: {...}` worked for me thanks @lonix1

**Comment by foad-salawati** [comment]
I have this problem too but I realized that I've omited the format option **format.metadata()** from logger instance:

**Comment by klemensz** [comment]
Is it possible to define `format` for `transports.MongoDB` alone - like we can do for `transports.Console`?

**Comment by pecko95** [comment]
@foad-salawati Hey, this option with setting `format.metadata()` at the bottom of the combine method works. But, I have another issue. When I use the `format.metadata()` so I can save the exception stack in my mongo db, it seems it bugs out the `exceptionHandlers` that I define while configuring the winston object. I define the exception handlers, in a separate transport File e.g. "exceptions.log", but the exceptions that occur are not saved there. Instead, it saves them in the file that I specified in the  `transports` array. Any idea what's going on?

And it specifically does this if I use the `format.metadata()` in the combine method. 😕

**Comment by bharukarupesh11** [comment]
> @CassiusHorvath i have the same function, but the meta property is empty, idk why, but if i pass the err like this winston.error(err.message, err); , in the console the stack is there

**Exactly! I'm also having the exact same issue. It's weird!** :(

**Comment by bharukarupesh11** [comment]
> @CassiusHorvath i have the same function, but the meta property is empty, idk why, but if i pass the err like this winston.error(err.message, err); , in the console the stack is there


@TheRealJota32 Below line has worked for me,
**winston.error(err.message, {metadata: err});**

Thanks, @lonix1 for the above line of code.

**Comment by ArashKarampour** [comment]
@CassiusHorvath 
@bharukarupesh11 
@yurijmikhalevich 
if you wrire like what you said it will just work for in mongodb but if you want it to work for console and log files as well as for mongodb you can write like this:

```
  winston.error(err.message, {  metadata: {
      message: err.message,
      name: err.name,
      stack: err.stack,
    },
  });
```

i've tested this and worked for me very well i all console , log file and mongodb.
good luck.

**Comment by Harvel-Kay** [comment]
apparently i had the same problem where the meta property in mongoDB transport was null: This is how i fixed it....

`
        const winston = require("winston")
        const { format } = require("winstone")
        
        winstone.add(new 
        winstone.transports.MongoDB({
        format:format.metadata()})

`

**Comment by sonmezerekrem** [comment]
> ```ts
> metaDataKeyName
> ```

Thank you very much this solves the problem. Also adds any additional fields logger.child() to metadata while transport to mongodb
