### ISSUE TITLE
Why is message stringified

### ISSUE THREAD

**Issue by eric-caslake** [winstonjs/winston-mongodb#151]
Why is the message coming out stringified in the Mongo collection, I would expect it to be a json object.

Getting this:
`"message" : "{ redirectResponse: { code: 'test' } }",`

Instead of this:
`"message": {
  "responseRedirect" : {
    "code": "test"
  }
}`

**Comment by yurijmikhalevich** [comment]
@eric-caslake this is because of how Winston works. You can pass any extra metadata you need as an object in the argument following message argument like: `logger.info('something happened', {redirectResponse: {code: 'test'}})`.

**Comment by painkkiller** [comment]
> @eric-caslake this is because of how Winston works. You can pass any extra metadata you need as an object in the argument following message argument like: `logger.info('something happened', {redirectResponse: {code: 'test'}})`.

This method don't work. Meta is always null, tested on  "winston-mongodb": "^5.1.1"  Simpler to write own than use this.
