### ISSUE TITLE
Store detailed information in the mongoDB document

### ISSUE THREAD

**Issue by freirart** [winstonjs/winston-mongodb#181]
Hi! I'm using `winston-express` as a middleware to intercept the request/response body and store it in a file.

When the request gets into the server, it's information is logged in the Console and stored in the File (by winston transports).

The document is stored in a JSON file and each document is something like 

```
{
	"meta":
	{
		"req":
		{
			... req info
		},
		"res":
		{
			... res info
		},
		"responseTime": some time
	},
	"level":"some level",
	"message":"some message",
	"timestamp":"some time"
}
```

I'd like to know if there is some way to store the whole object "meta" into the MongoDB document. 

"level, "message" and "timestamp" is stored just fine, but the "meta", __that is crucial to me__, remains as __null__.

**Comment by yurijmikhalevich** [comment]
Hi @freirart! Default key that `winston-mongodb` uses to store metadata is `metadata`. Is anything being saved there? You can try passing `metaKey: 'meta'` to the `winston-mongodb` transport constructor and see if it will help you.

**Comment by freirart** [comment]
The `metaKey: 'meta'` did the trick.

Thank you, @yurijmikhalevich !
