### ISSUE TITLE
How to set the db name?

### ISSUE THREAD

**Issue by ben4d85** [winstonjs/winston-mongodb#193]
**How can I specify the database name that winston-mongodb uses?**

NB: Due to my setup, I am unable to include the database name in the connection string. 

As a starting point, consider that `mongoose.connect` accepts an options object that can have a `dbName` property. Could you take a similar approach for winston-mongodb? Something like the below?

```
myLogger.add(
        new transports.MongoDB({ 
            db: mongoURI, // MongoDB connection string WITHOUT a database name
            dbName: "winston", // TODO: Make this work
            collection: 'logs',
        }
    ));
```

Right now, the database created by winston-mongodb is called 'test'. I want to name it 'winston' instead.

**Comment by kedoska** [comment]
@ben4d85 if you append the name to your `mongoURI`, it should be ok

```ts
    transports: [
      new winston.transports.Console(),
      new winston.transports.MongoDB({
        ...
        db: `${process.env.MONGO_DB_URL}/${process.env.MONGO_DB_NAME}`,
        options: { useNewUrlParser: true, useUnifiedTopology: true },
        collection: 'logs',
        ...
      }),
```

**Comment by millerdk12** [comment]
I have created a [pull request](https://github.com/winstonjs/winston-mongodb/pull/205) for this one, not sure if this project is still actively maintained.

By passing in a new connection URI string, an additional connection would be made. I would prefer to have the option of using a pre-connected mongo client.

A work around is to use the pre-connected mongoose instance, but this generates a deprecated warning.
```js
const transport = new winston.transports.MongoDB({
  db: mongoose.connection.useDb('otherDBName'),
});
```

**Comment by DABH** [comment]
Closing this issue since https://github.com/winstonjs/winston-mongodb/pull/205 has been merged -- thanks again!

**Comment by millerdk12** [comment]
Thanks for getting that merged in @DABH! Were you able to get npm updated? I'm still seeing the version from 2 years ago.

**Comment by DABH** [comment]
Apparently I have permissions on GitHub but not NPM — I’ve asked @yurijmikhalevich if I can get NPM permissions but stay tuned :)

If it’s urgent you can always point package.json to the master branch of the GitHub repo ;)

**Comment by millerdk12** [comment]
Great thanks! Nope, it's not urgent. Just wanted to make sure we didn't miss that piece.
