### ISSUE TITLE
Deprecation warning { useUnifiedTopology: true } when using mongoose v>6.x

### ISSUE THREAD

**Issue by mp3846** [winstonjs/winston-mongodb#196]
I'm using:
mongoose 6.1.6
winston 3.4.0
winston-mongodb 5.0.7
this version of winston-mongodb has mongoose 5.10.5 in its devDependencies and this deprecation warning keeps printed on the console:

`(node:18472) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use node --trace-warnings ... to show where the warning was created)`

It seems easily can be fixed by passing that option (and subsequently `{ useNewUrlParser: true }`) to the connect method of mongoose or by updating mongoose and adapt winston-mongodb with it

**Comment by DABH** [comment]
PR welcomed!

**Comment by hugoivankm** [comment]
Hi,
I am new to open source but this request seems pretty straightforward. If I am not mistaken it would be solved by adding 
`{useNewUrlParser: true }` to the default option. Can I help with that?

**Comment by wbt** [comment]
Help is welcome, though I think it's a little more involved than just passing that option - it would silence the warning, but are we using the old Server Discovery and Monitoring Engine?  If so, would this break something? If not, can we just avoid the performance hit of activating hefty new features?

**Comment by mp3846** [comment]
Can be solved by passing it in options prop

new transports.MongoDB({
        db: process.env.DB_URL,
	collection: 'logs',
	level: 'error',
	options: {
		useUnifiedTopology: true
	}
)
