### ISSUE TITLE
Authentication error when passing the database

### ISSUE THREAD

**Issue by bralandealmeida** [winstonjs/winston-mongodb#198]
Hi, I'm opening this issue because I'm not sure if this only happens to me.

I'm having trouble connecting to the database when in the mongo url I pass the database. I'm using a structure similar to this:

```
const logger = winston.createLogger({
  levels: customLevels,
  format: winston.format.combine(
    winston.format.errors({ stack: true }),
    winston.format.json(),
    winston.format.timestamp(),
  ),
  transports: [
    new winston.transports.MongoDB({
      db: `mongodb://user:pass@host:port/database`,
      tryReconnect: true,
      collection: 'logs',
      options: { useNewUrlParser: true, useUnifiedTopology: true }
    }),
  ],
});
```

But when trying to connect, I get the following error:

```
winston-mongodb: will try reconnecting in 10 seconds
winston-mongodb: error initialising logger MongoError: Authentication failed.
```
When I remove the database from the connection string from mongodb it connects and creates a database called "test" on mongo. The username and password are correct, as I entered the same data to create the database I am trying to connect. 

Anyone else going through something similar?

**Comment by wbt** [comment]
@bralandealmeida you might find more luck on StackOverflow, if you don't find others encountering the same issue here.
I assume you are replacing `user`, `pass`, `host`, `port`, and `database` with their appropriate values and the user has permissions to use that specific database, not just create databases.

**Comment by bralandealmeida** [comment]
> 

Yes. I replace the values with environment variables and, as I said, when I remove the database from the mongodb connection uri it works normally 🤨.

**Comment by wbt** [comment]
That suggests to me that the user you're trying to connect with might not have the necessary permissions on the database you're trying to use.

**Comment by bralandealmeida** [comment]
For those who are facing this problem, we have to pass the authentication database, otherwise mongoDB will try to authenticate itself using the database we are informing.

` db: mongodb://user:pass@host:port/database?authSource=admin`
