### ISSUE TITLE
[Feature Request]: Make CI work

### ISSUE THREAD

**Issue by DABH** [winstonjs/winston-mongodb#225]
### 🔎 Search Terms

CI, GitHub Actions, Linting

### The vision

Can anyone in the community pitch in and finish the work of making our CI work?

1. I fixed a bunch of linter errors, but there are a few more to go (just clone, `npm i --dev`, and `npm run lint` to see the list)
2. Even once we fix the linter errors, the CI tests won't pass because a local MongoDB server needs to be running.  It looks like this is achievable with GitHub Actions: https://github.com/marketplace/actions/mongodb-in-github-actions .

Would be a huge help to the community if someone could step up for this, since right now (and for a long time) we've been flying blind with releases and MongoDB compatibility/testing.  Huge huge thanks to anyone able to take this on.

**Comment by curledUpSheep** [comment]
@DABH regarding the MongoDB compatibility testing:

- Could it be useful to use something like [mongodb-memory-server](https://www.npmjs.com/package/mongodb-memory-server) so anyone (including CI) can run the tests without explicitly having MongoDB installed?
- What versions of MongoDB need to be included in the testing? Is it sufficient to use the current latest version (6.0) or should other versions that have not yet reached end-of-life status be included?

**Comment by DABH** [comment]
Hi! On your two points:
1. That sounds great!!
2. Ideally I’d vote for a test matrix with 4.4, 5.0, and 6.0 (GitHub Actions makes it pretty easy to set up a matrix of tests), but if that is way too hard for whatever reason, just 6.0 is way better than nothing :)

Excited/grateful for anything you could do!!

**Comment by curledUpSheep** [comment]
@DABH let me know what you think :) https://github.com/winstonjs/winston-mongodb/pull/227

**Comment by DABH** [comment]
Thank you for this heroic effort!  This is really appreciated and I expect will benefit the project for years to come :)

**Comment by curledUpSheep** [comment]
@DABH now that CI is working: any idea when a new version would be published on npm?

It would be very convenient for me to have an officially published version that includes the fix from my other recently merged PR :)

**Comment by DABH** [comment]
@yurijmikhalevich Could you do a minor release?  It looks like I don't have write permissions on NPM.  Alternatively/in addition, can you add me as a writer on npm?  I thought the winston team had write access to all winston packages on npm but seems like not.  Thanks in advance!
