### ISSUE TITLE
[Bug]: Code snippet hangs up when logging to MongoDB.

### ISSUE THREAD

**Issue by elf-alchemist** [winstonjs/winston-mongodb#244]
### 🔎 Search Terms

winston-mongodb, hanging

### The problem

When running a code snippet of `winston` and `winston-mongodb` on the command line (`ts-node ./scripts/node-logger.ts`), the code will write successfully to the database, but will hang and not stop, until I use `Ctrl+C`, this does not happen with `File` or `Console` transports. Using version 6.0 of MongoDB on a docker container.

### What version of Winston presents the issue?

v3.10.0

### What version of Node are you using?

v20.7.0

### Minimum Working Example

```typescript
// typescript: v5.2.2
// winston-mongodb: v5.1.1
import winston from 'winston';
import { MongoDB } from 'winston-mongodb';

const { createLogger, format } = winston;
const { combine, timestamp, json } = format;

const time_format = 'YYYY-MM-DDTHH:mm:ss';

function main() {
  const mongo_logger = createLogger({
    level: 'info',
    format: combine(timestamp({ format: time_format }), json()),
    transports: [
      new MongoDB({
        db: 'mongodb://localhost:27017',
        collection: 'logs',
        metaKey: 'metadata',
        options: { useUnifiedTopology: true },
      }),
    ],
    defaultMeta: true,
  });

  const { name, message } = new Error();

  const context = { client: '...', api: '...', version: '...' };

  mongo_logger.log('info', JSON.stringify({ name, message, ...context }));
  mongo_logger.log('warn', JSON.stringify({ name, message, ...context }));
  mongo_logger.log('error', JSON.stringify({ name, message, ...context }));
}

main();
```

**Comment by curledUpSheep** [comment]
I think your code hangs because it still has an open connection to the DB.

Instead of passing a connection URL to winston-mongodb, you can pass a MongoClient (see the README of the repository).
You can then close this MongoClient when you are done logging.

**Comment by elf-alchemist** [comment]
Dang, that did it, thanks @curledUpSheep.
