### ISSUE TITLE
Having trouble streaming logs

### ISSUE THREAD

**Issue by djMax** [winstonjs/winston-mongodb#38]
I'm trying to stream the logs but I get "[Error: Connection was destroyed by application]" like every 10 seconds. Additionally it seems to call me with the same message sometimes:

    var lastMsg, logStream = mongodbLogger.stream({includeIds:true});
    logStream.on('log', function (log) {
        if (lastMsg == String(log._id)) {
            // I have no idea why this happens, but it does.
            return;
        }
        lastMsg = String(log._id);
        /* Here I print it out or do stuff */
    }).on('error', function (e) {
        /* This happens a lot, and then it stops streaming */
        console.log('winston streaming error.',e);
    });

**Comment by jordonias** [comment]
I'm getting a similar issue.
```
var winston = require('winston');
require('winston-mongodb').MongoDB;
var logger = module.exports = new winston.Logger;

logger.add(winston.transports.MongoDB, { db: 'test' }); 

logger.error('hi');

logger.stream({ start: -1 }).on('log', function(log) {
  console.log(log);
});
```

**Comment by 39dotyt** [comment]
Should be checked against winston-mongodb v1.0.0.
