### ISSUE TITLE
Cannot find module 'winston-mongodb'

### ISSUE THREAD

**Issue by amicke** [winstonjs/winston-mongodb#46]
Installed winston-mongoldb with npm (npm install winston-mongodb) it installs successfully. I then start my server (node server.js) and get the following error:

module.js:338
    throw err;
    ^
Error: Cannot find module 'winston-mongodb'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

I can find winston-mongodb inside the node_modules folder. This is how I load the module:
var winston = require('winston');
var MongoDB = require('winston-mongodb').MongoDB;

Is there something in the new release that break this? (Downgraded to 0.5.1 and everything works fine)

**Comment by 39dotyt** [comment]
Fixed in https://github.com/winstonjs/winston-mongodb/commit/546e805ed2c40bea74eaa089e17b2815fa3ea226. Thank you for reporting.
