### ISSUE TITLE
logger is dropping logs while it's waiting to authorizeDb and createCollection

### ISSUE THREAD

**Issue by dankahle** [winstonjs/winston-mongodb#48]
https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L123

In the following log queueing code, the queue determination is dependent on this.mainDb, 

  if (!this.mainDb) {
    this._opQuery.push({
      method: 'log',
      args: arguments
    });
    return;
  }

But... in the following code, we turn on this switch before we authorize and createCollection. Any logs coming in after this.MainDb exists will not be queued. Somewhere between the authorizeDb and createCollection calls, the logging code is dropping the logs. Not in the mood to pull my hair out over it, as clearly there's an obvious bug here, the queue switch should be thrown in the createCollection callback, right before calling processOpQuery. Probably not cool to be trying to write to a database while you're currently authorizing to it, or to a collection while you're creating a collection, in my case the collection already exists, but if it didn't, you could have code trying to log to a collection before you created it.

  if ('string' === typeof this.db) {
    mongodb.MongoClient.connect(this.db, this.options, function(err, db) {
      if (err) {
        console.error('winston-mongodb: error initialising logger', err);
        return;
      }
      self.mainDb = db;
      authorizeDb(function() {
        createCollection(processOpQuery);
      });
    });
  } else {
    this.mainDb = this.db;
    authorizeDb(function() {
      createCollection(processOpQuery);
    });
  }
};

maybe something like:

this.queueLogs = true;

  if (this.queueLogs) {
    this._opQuery.push({
      method: 'log',
      args: arguments
    });
    return;
  }

authorizeDb(function () {
createCollection(function(err) {
   self.queueLogs = false;
   processOpQuery()
}
}

Here's my code, the readme.txt explains it, but simple enough. Just gets in that sweet spot where we're calling authorizeDb and createCollection and tries to log... to no avail.

https://gist.github.com/dankahle/06d21584a6bed63cc7cf

**Comment by 39dotyt** [comment]
Thank you for your code, I will review it later.

Have you tried to run this test https://github.com/winstonjs/winston-mongodb/blob/master/test/winston-mongodb-preconnected-test.js?

**Comment by dankahle** [comment]
No I haven't sorry, but it falls short in this case as if it would go one step further (log), then the log would probably find that sweetspot where winston-mongodb was authorizing/creatingcollection while the log was trying to happen. Something goes wrong there, but no surprise, as you probably shouldn't try to authrorize while your writing on the same connection. Yesterday I put in my fixes, the promise fix I had talked about and the other one I talk about above, and worked like a charm. I thought between the promise fix and mongoose, I would just require the db and logger and no more async module waiting, but sadly the mongoose underlying native driver didn't store the logs for some reason, so not quite the same as just opening a native driver. The answer of course is to have winston-mongodb take a mongoose connection as well, but then there's that whole authorization thing... I don't understand that. I.e. if you have a db connection, they the auth has already been done, why redo it? If that wasn't there, you could plug mongoose in and just use it as if the db was ready, mongoose queueing the db commands for you. With the native driver, all works just fine with the promise, which is yet another option. Then at least all modules requiring a logger need not do anything special, the logger simply queueing logs until its ready as it does for the connection string option.

**Comment by dankahle** [comment]
Was gonna do a quick PR of my changes, but can't make any sense of the tests. Look like they're there just to add to winston's test suite, but can't see how they would even plug in, or how they would be asserted as well. I'll just PR my changes so you can see what I was thinking.
