### ISSUE TITLE
Node application hangs

### ISSUE THREAD

**Issue by ejbrennanjr** [winstonjs/winston-mongodb#51]
Hello - 
I am using winston-mongo v1.1.0.
I have a simple app.js that runs a few .log commands.  Initially, I did this just using Winston native file and console based transports. This worked fine.  The app starts up, logs to the file/console, and shuts down normally.  But, when I require winston-mongo in my app.js and add it as a transport, when I run the otherwise same app.js the node application successfully logs to Mongo but does not shut down.  I have to ctrl-c to end the process.  Can you provide any insight to what I'm doing wrong?
- EJB

**Comment by 39dotyt** [comment]
Hi, @ejbrennanjr.

You are doing everything fine. This happens because winston-mongodb is an asynchronous module and MongoDB connection is persistent. If you want to shut down your application, please, close your mongodb connection or destroy winston-mongodb instance.
