### ISSUE TITLE
Renaming default collection breaks stuff

### ISSUE THREAD

**Issue by steve-p-com** [winstonjs/winston-mongodb#52]
In 1.1.0, the default collection was changed from 'logs' to 'log'. I would classify this as a breaking change, because although logs continue to be written, that is only half of the story. Logs are not useful without a means to view or filter them, and they are no longer visible to any other code that reads the 'logs' collection. This unexpectedly broke my server code.

I know  you can work around this by changing the application to specify the collection name, but that's not really the point. The idea of defaults is so that you don't have to specify them. Under semver rules, breaking changes should only be made when the major version number changes, not minor ones.

**Comment by 39dotyt** [comment]
My mistake. Thank you for mentioning this. And sorry for the inconvenience.

But, now it's also will be a mistake to unpublish this version from npm. I will be more careful in the future and I hope that others will read the changelog.

**Comment by steve-p-com** [comment]
Thanks. I agree that it would be a mistake to reverse the change now it's happened. I have changed all my projects to specify the collection name now.
