### ISSUE TITLE
Stack is not being included in meta

### ISSUE THREAD

**Issue by gmahomarf** [winstonjs/winston-mongodb#53]
[These lines](https://github.com/winstonjs/winston-mongodb/blob/master/lib/helpers.js#L20-L28) no longer work to copy stack to the ```prepared``` object. ```common.clone``` now returns the same object when it's an instance of ```Error```, as seen [here](https://github.com/winstonjs/winston/blob/master/lib/winston/common.js#L83-L85)

**Comment by 39dotyt** [comment]
Fixed. Thank you for reporting.

**Comment by gmahomarf** [comment]
Awesome! Thanks for the quick fix.
