### ISSUE TITLE
Problems installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by kokujin** [winstonjs/winston-mongodb#54]
kerberos@0.0.14 install /home/kokujin/development/research/text_express/node_modules/winston-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/kokujin/development/research/text_express/node_modules/winston-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
 CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: g++: Command not found
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 127
make: Leaving directory `/home/kokujin/development/research/text_express/node_modules/winston-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-49-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kokujin/development/research/text_express/node_modules/winston-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
winston-mongodb@1.1.2 node_modules/winston-mongodb

**Comment by 39dotyt** [comment]
> make: **g++: Command not found** make: *** 

You should install g++ it is required by the node-gyp to build kerberos which is required for the mongodb driver.

You may install it using

```
$ sudo aptitude install build-essentials
```

**Comment by kokujin** [comment]
This maybe should be in the installation instructions then.

**Comment by 39dotyt** [comment]
Maybe, but this also may be not clear because this is the dependency of the mongodb-core, which may be disabled in the future.

By the way, this requirement is not mentioned neither in the mongodb-core or kerberos documentation.
