### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Redsandro** [winstonjs/winston-mongodb#56]
I cannot build this on Ubuntu 14.4.2. Tried `1.2`.x and `1.1.x`

```
> kerberos@0.0.15 install /var/www/test/node_modules/winston-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/var/www/test/node_modules/winston-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/var/www/test/node_modules/winston-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/test/node_modules/winston-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
winston-mongodb@1.2.0 node_modules/winston-mongodb
└── mongodb@2.0.46 (es6-promise@2.1.1, readable-stream@1.0.31, mongodb-core@1.2.19)
```

**Comment by Redsandro** [comment]
Solution: `sudo apt-get install libkrb5-dev`

This is the first time I needed some linux package as a dependency. Is there some way to track and record these? As in, how can I make `npm` __NOT__ break an otherwise running installation when attempting to update packages, when certain linux dependencies aren't met?

**Comment by phillipwei** [comment]
I experienced this same build failure, but on windows.

**Comment by 39dotyt** [comment]
@Redsandro keep in mind that `kerberos` is MongoDB itself dependency, not winston-mongdb. If you have any questions regarding this it's better to ask them in the node-mongodb-native repo (more exactly, in mongodb-core https://www.npmjs.com/package/mongodb-core).

**Comment by Redsandro** [comment]
Good to know. This is interesting, because I already have mongodb-native running with my app, without said package installed. Perhaps it was introduced in a semi-recent release?

**Comment by 39dotyt** [comment]
I'm not sure. I will investigate this today. Anyway, Kerberos mentioned as optional dependency of mongodb and you can prevent it from installing by executing npm with --no-optional argument (or something similar, you can look it up in the npm documentation). Maybe there is a way to specify this argument in package.json.

**Comment by Redsandro** [comment]
I didn't know about the `--no-optional`.

> Maybe there is a way to specify this argument in package.json

That would be a solution. A quick glance doesn't look like it. Surely this can be an issue for other packages as well, so it would make sense if there's some kind of option or safeguard for this.

Interesting.

I'm not sure why `node-mongodb` (optionally) uses kerberos. I authenticate using `authenticate()` on a connection just fine. Perhaps kerberos is a non-plaintext alternative.

**Comment by 39dotyt** [comment]
> Perhaps kerberos is a non-plaintext alternative

This is pretty close.
According to wikipedia, kerberos /ˈkərbərəs/ is a computer network authentication protocol which works on the basis of 'tickets' to allow nodes communicating over a non-secure network to prove their identity to one another in a secure manner.

> A quick glance doesn't look like it

Same for me.

What if you are passing this option to `npm install` itself?
