### ISSUE TITLE
Unable to reconnect if MongoDB is not running when winston-mongodb starts

### ISSUE THREAD

**Issue by jingzhaoou** [winstonjs/winston-mongodb#58]
If winston-mongodb is already running, it is able to reconnect to MongoDB automatically. However, if MongoDB is not running when winston-mongodb starts, winston-mongodb throws the following error and the MongoDB connection is broken permanently. 
```
winston-mongodb: error initialising logger { [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017' }
```
Wonder if there is any quick way to resolve this issue. I am using winston-mongodb in a critical project and reconnect is very important. I appreciate any insights. 

Thanks a lot!
Jingzhao

**Comment by Adam-Burke** [comment]
I have the same issue. Help.

**Comment by 39dotyt** [comment]
Hi @jingzhaoou , @Adam-Burke .

Can you say how do you initializing winston-mongodb?

**Comment by Adam-Burke** [comment]
Hi @jingzhaoou. I have noticed that the problem fails only when I am not connected to the internet on a single machine I am using. When connected to the internet it connects fine. Also it seems to work fine on my laptop with the identical code both connected and not connected to the internet. 

The machine it fails on is a specific machine where I recently used a  mongorestore to duplicate a database. The only thing I can notice that is different amongst the implementations is one uses mongodb 3.2 and the other uses mongodb 3.2.4. process.env.DB_URI in the code below resolves to mongodb://localhost:27017/LiGr.

"use strict";
var winston = require('winston');
var MongoDB = require('winston-mongodb').MongoDB;
var fs = require('fs');

winston.emitErrs = true;
var logger = new winston.Logger({
    transports: [
        new (winston.transports.Console)({
            handleExceptions: true,
            humanReadableUnhandledException: true,
            json: false,
            colorize: true
        })
    ],
    exitOnError: false
});
logger.add(MongoDB, {
    db: process.env.DB_URI,
    level: 'error',
    collection: 'logs'
});
module.exports = logger;
module.exports.stream = {
    write: function (message, encoding) {
        logger.info(message);
    }
};

Thank you for any help. 

Regards,

Adam

**Comment by 39dotyt** [comment]
@Adam-Burke , @jingzhaoou , please give a try to winston-mongodb 1.4.0 with tryReconnect option.

**Comment by jingzhaoou** [comment]
I truly appreciate the quick improvement! I tried 

```
winston.add(winston.transports.MongoDB, {
    tryReconnect: true
});
```

and things work great!

Cheers,
Jingzhao

**Comment by 39dotyt** [comment]
@jingzhaoou great to hear this!

Think, that the issue may be closed now.

@Adam-Burke have you checked if it fixed the issue for you?

**Comment by elhigu** [comment]
And for anyone else who is interested how often reconnect is ran... its done every 10 seconds.

**Comment by sebasgross** [comment]
I need help with this!
`const winston = require('winston');
require('winston-mongodb').MongoDB;

const winstonLogger = winston.createLogger({
  format: winston.format.json(),
  transports:[
    new (winston.transports.Console),
    new (winston.transports.MongoDB)({
      db: process.env.DB,
      collection: 'error-logs',
      storeHost: true,
      expireAfterSeconds: 2630000,
      tryReconnect: true
    })
  ],
  exitOnError: false,
});

module.exports = winstonLogger
`

**Comment by sebasgross** [comment]
I also need help with this. 
This is my winston.js 
`const winston = require('winston');
require('winston-mongodb').MongoDB;

const winstonLogger = winston.createLogger({
  format: winston.format.json(),
  transports:[
    new (winston.transports.Console),
    new (winston.transports.MongoDB)({
      db: process.env.DB,
      collection: 'error-logs',
      storeHost: true,
      expireAfterSeconds: 2630000,
      tryReconnect: true
    })
  ],
  exitOnError: false,
});

module.exports = winstonLogger`
