### ISSUE TITLE
Connect to MongoDB using with different authentication database

### ISSUE THREAD

**Issue by fatihayyildiz** [winstonjs/winston-mongodb#59]
Hi,

After searching many hours I need to create this issue.Cause I didn't optimal solution.I rent mongodb as a service from one company and they created user which is not using "admin" database for authentication database.For this reason I changed mongoose connection as descripted in this issue. 
[https://github.com/Automattic/mongoose/issues/1114](Mongoose Issue 1114)

But when I tried this code :
```
var logger = new(winston.Logger)({
    transports: [
        new(winston.transports.Console)(),
        new(winston.transports.MongoDB)({
            db: 'mongodb://localhost/dataDB?authSource=customAuthDB',
            username: config.dbUsername,
            password: config.dbPassword,
            handleExceptions: config.winstonErrorHandle
        })
    ],
    exitOnError: false
});
```
I am getting this error :

```
winston-mongodb: error initialising logger { 
[MongoError: Authentication failed.]
name: 'MongoError',
message: 'Authentication failed.',
ok: 0,
code: 18,
errmsg: 'Authentication failed.' }
```

So I got stuck when I am authenticate with using customAuthDB. How can I fix this ?

**Comment by 39dotyt** [comment]
Hi @fatihayyildiz.

If you are using db uri, try passing username and password within it instead of using parameters:

```javascript
mongodb://username:password@localhost/dataDB?authSource=customAuthDB
```

Please, report whether it worked.

Alternatively, you may pass pre-connected database connection object to as a db parameter to winston-mongodb.

**Comment by fatihayyildiz** [comment]
Hi @39dotyt 

I already test that mongodb uri but our password has wildcard characters. When try that password,I get  URI malformatted error. 

Could you further describe pre-connected database connection way or can you share some script for this ?

**Comment by 39dotyt** [comment]
> I already test that mongodb uri but our password has wildcard characters. When try that password,I get URI malformatted error.

Have you tried escaping those characters?

**Comment by fatihayyildiz** [comment]
What's mean escape ? I cannot change password for security reasons. This password for production environment.

**Comment by 39dotyt** [comment]
Try using `encodeURIComponent(password)` on password before.

**Comment by fatihayyildiz** [comment]
@39dotyt 

Its working correctly.Thank you so much.

**Comment by 39dotyt** [comment]
@fatihayyildiz you are welcome ;-)
