### ISSUE TITLE
cappedMax  not working??

### ISSUE THREAD

**Issue by jeffthompson1971** [winstonjs/winston-mongodb#60]
I know the config I'm using is getting picked up because i use the 'label' option and now i see that label on every document.   but the cappedMax is  not being honored.. my config is below.   What's up?
...
  new(winston.transports.MongoDB)({
            db: config.db,
            level: 'info',
            handleExceptions: true,
            exitOnError: false,
            cappedMax: 25,
            label: "TEST LABEL"

        })

**Comment by 39dotyt** [comment]
Can you provide minimum runnable example?

**Comment by 39dotyt** [comment]
Is config.db uri string?
Are you creating a new collection or connecting to the existed one?
Try removing 'log' collection from the database before running your application with this config.
