### ISSUE TITLE
Decolorize log messages received through stream

### ISSUE THREAD

**Issue by santanu-biswas** [winstonjs/winston-mongodb#62]
I use [express](http://expressjs.com/en/guide/migrating-4.html#changes) for my node.js apps, which in turn uses [morgan](https://www.npmjs.com/package/morgan) for logging. I use the following code for redirecting morgan logging to winston:

```
var express = require('express');
var winston = require('winston');
var MongoDB = require('winston-mongodb').MongoDB;

winston.setLevels( winston.config.npm.levels );
winston.addColors( winston.config.npm.colors );

var logger = new (winston.Logger)({
    transports: [
        new winston.transports.Console({
            level: 'info',
            colorize: true,
            timestamp: true
        }),
        new winston.transports.MongoDB({
            level: 'info',
            label: true,
            timestamp: true,
            handleExceptions: true,
            db: 'appdb,
            collection: 'applog',
            tryReconnect: true
        })
    ],
    exceptionHandlers: [
        new winston.transports.File({
            filename: 'log/exceptions.log',
            humanReadableUnhandledException: true,
            timestamp: true
        })
    ]
});

logger.stream = {
    write: function(message, encoding){
        logger.info(message.slice(0, -1));
    }
};

app.use(morgan('dev', { stream: logger.stream }));
```

This works fine for the Console transport, however, since morgan colorizes parts of the log message, It results in the message getting saved in mongodb collection with the color codes as following:

> \u001b[0mGET /v1/countries \u001b[32m200 \u001b[0m5.956 ms - 8276\u001b[0m

I tried replacing logger.stream in my code as following:

```
logger.stream = {
    write: function(message, encoding){
        logger.info(message.slice(0, -1).replace(/\u001b\[[0-9]{1,2}m/g, ''));
    }
};
```

This removes the color codes but then it also removes the colors for Console transport. Slice removes the unnecessary newline at the beginning of the morgan log entry

I want to keep the colors for Console transport but want to remove it from File & MongoDB transports. For File transport I can use the [formatter](https://github.com/winstonjs/winston#adding-custom-transports) option, but don't have that option in MongoDB transport.

**Is there any readily available solution for this?**

The simplest solution that I can think of is to change the code [line](https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L257) of in winston-mongodb:

`entry.message = msg;`

to

`entry.message = msg.replace(/\u001b\[[0-9]{1,2}m/g, '');`

I am really not sure why would anyone would want to save the color code in MongoDB log, but assuming that someone might actually require the color coded log entry, **decolorize** can be added as an option for the MongoDB transport, and then the code can be:

`entry.message = self.decolorize ? msg.replace(/\u001b\[[0-9]{1,2}m/g, '') : msg;`

If this is an acceptable feature/solution, I am willing to submit a PR for this.

**Comment by 39dotyt** [comment]
Hi,

Thank you for the PR. I think, that it's better with 'decolorize' option for now, because color codes maybe a part of a log message itself.

Checkout v1.6.0. It includes your changes.
