### ISSUE TITLE
Timestamp format

### ISSUE THREAD

**Issue by miton18** [winstonjs/winston-mongodb#64]
How can we set format of Timestamp to a real timestamp ? 

not 2016-06-12T15:42:33.337Z
but 1465746153

**Comment by 39dotyt** [comment]
Hi @miton18,

It is stored in [ISODate format](https://docs.mongodb.com/v3.2/core/shell-types/). You can query logs by comparing it to with Date objects.

Why do you need it to be a unix timestamp?

**Comment by miton18** [comment]
It's easiest for all langage to parse it

**Comment by 39dotyt** [comment]
@miton18 mongodb drivers should allow you to get it in unix timestamp.
