### ISSUE TITLE
MongoError: Index name can not be empty

### ISSUE THREAD

**Issue by yazla** [winstonjs/winston-mongodb#68]
Hello there,

I am getting this error when trying to connect
```
MongoError: Index name can not be empty
```
But using the same db without winston works just fine, Can you please advice.

Thanks.

**Comment by yazla** [comment]
Well, I found the reason,

```
col.createIndex({timestamp: -1}, function(err) {
        cb(err, db);
      });
```
this is not supposed to work, there should be an index name as the first parameter.
How could it work for anyone at all?

**Comment by 39dotyt** [comment]
Hi. Why do you think so?

http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#createIndex

**Comment by 39dotyt** [comment]
Fixed.
