### ISSUE TITLE
Replicaset in mongodb

### ISSUE THREAD

**Issue by j0n4s** [winstonjs/winston-mongodb#70]
how config multiples hosts in new version, for example my config is: 

new (winston.transports.MongoDB)({
     name: 'mongo-info',
    db: "mongodb://user:pass@host1,host2/db_name"
     collection: '<dbcollection>',
     storeHost: true,
     level: 'info',
     timestamp: true
  }),

but new version 1.6 does not work...

**Comment by 39dotyt** [comment]
This dbUri should work.
Why collection name is empty?

**Comment by geomartinez** [comment]
Having a similar problem here... mongo installation is a replica set >> winston-mongodb able to actually create the collection but do not add any entries into collection. My file and console transports work perfectly. Below are code excerpt...
dbLogOptions.db=config.mongoURI;
//dbLogOptions.username=config.mongoUser;
//dbLogOptions.password=config.mongoPassword;
dbLogOptions.level='info';
dbLogOptions.collection='ctnLogs';
dbLogOptions.capped=true;
dbLogOptions.dbUri=config.mongoURI;

winston.add(winston.transports.MongoDB, dbLogOptions);
...
//config.json excerpt
"mongoURI":"mongodb://<user>:<password>@<hostFQDN>:27017/od",

...
winston.info('Some text');

I'm pretty sure my FQDN is pointed to the primary mongo replica. Am I missing anything?

**Comment by 39dotyt** [comment]
Hi @geomartinez. Thank you, will test it.

**Comment by MichaelTurbe** [comment]
Having the same issue; logging to a development database working fine, logging to a production replicaset is creating no records.

**Comment by 39dotyt** [comment]
@j0n4s you url is missing `?replicaSet=<rsName>` parameter. It works fine for me with the valid url.
@geomartinez, @MichaelTurbe can you post url you are using?
