### ISSUE TITLE
Add more data

### ISSUE THREAD

**Issue by adrienbarreau** [winstonjs/winston-mongodb#76]
Hi,

Is there any way to set more data to the entries ?
I use 'hostname' and 'label' and i'd like to add another one like 'scriptName' for example.

**Comment by 39dotyt** [comment]
Hi @adrienbarreau ,

As option you can manually pre-process log entries and add needed fields to them before sending to `winston`.

**Comment by 39dotyt** [comment]
You can also read this thread. https://github.com/winstonjs/winston/issues/200

**Comment by adrienbarreau** [comment]
I'd have to set 'scriptName' in every log call. That's not optimal.
Can't we have something like this ?

`
options.preMetaData = {
    scriptName: process.env.scriptName
};
winston.add(winston.transports.MongoDB, options);
`

winston-mongodb.js

`
if (this.preMetaData) {
    Object.keys(this.preMetaData).forEach(function(key){
        entry[key] = this.preMetaData[key];
    })
}
`

**Comment by 39dotyt** [comment]
@adrienbarreau 

> That's not optimal.
How is this less optimal than adding exact same logic to the `winston-mongodb` code?

This shouldn't be done not on `winston-mongodb` level. This should be done either on `winston` or on your application level.
