### ISSUE TITLE
Logged data are altered

### ISSUE THREAD

**Issue by adrienbarreau** [winstonjs/winston-mongodb#79]
When I call my data asynchronously after being logged, it has been modified.

As it's not easy to describe, I created an example [here](https://github.com/adrienbarreau/winston-mongodb-bug-example)

Note that if I remove winston.transports.MongoDB from winston transports, everything is ok.

**Comment by 39dotyt** [comment]
Hi. Thank you for the report. Fixed in #2.0.2.

**Comment by 39dotyt** [comment]
In 2.0.3 :-)
