### ISSUE TITLE
Logs not stored in collection

### ISSUE THREAD

**Issue by tibeoh** [winstonjs/winston-mongodb#80]
Hi,

I try to add a MongoDB transport type. The collection is created but no data is stored...

`logger.js`
```
var winston = require('winston');
require('winston-mongodb').MongoDB;

winston.configure({
	transports: [
		new (winston.transports.Console)({ json: false, colorize: true }),
		new (winston.transports.MongoDB)({ db: 'mongodb://localhost/tests', collection: 'logs', level: 'info', capped: true }),
	]
});

module.exports = winston;
```

And in one of my file:
```
var logger = require('./logger.js')

winston.log('info', 'transaction ok');
// or
logger.info('transaction ok');
```

The log display in my terminal but never stored in collection. What is wrong?

Thanks guys for your help ;)

**Comment by tibeoh** [comment]
#75 It's the similar issue.

**Comment by ARenfroe** [comment]
Did anyone find a work around for this?  I am only experiencing it in my codeship builds.

**Comment by 39dotyt** [comment]
@ARenfroe will be fixed ASAP, please fallback to 1.6.0 version.

**Comment by ARenfroe** [comment]
@39dotyt thank you.

**Comment by skotturi** [comment]
I'm seeing this with both v2.0.0 and 1.6.0 running node 6.9.1 and mongoose 4.7.1 

is there another interim workaround, such as dropping the indexes on the winston-mongo collections and reinitiating them?
