### ISSUE TITLE
_id is set to String output of object

### ISSUE THREAD

**Issue by jehartzog** [winstonjs/winston-mongodb#92]
I'm using this in a Meteor project and when I look at my MongoDB, the database entries look like this:
```
{
  _id: ObjectId("58ad97d9e87b1adec5c510a7"),
  timestamp: 2017-02-22 13:53:29.445Z,
  etc...,
}
```
Is that the intended behavior of the _id field, rather than just being the alphanumeric portion? If not, let me know and I can take a shot at creating a PR to fix it.

Here is the code I'm using to startup this plugin:
```
import winston from 'winston';
import 'winston-mongodb';
...
logger = new winston.Logger({
  transports: [
    new winston.transports.MongoDB({
      db: process.env.MONGO_URL,
      handleExceptions: true,
      level: 'debug',
    }),
  exitOnError: false,
});
```
Also my project was also affected by issue #90, I saw the PR so looking forward to that fix :).

**Comment by 39dotyt** [comment]
Hi @jehartzog. Yes, it is. Please, refer to MongoDB docs for explanation https://docs.mongodb.com/manual/reference/method/ObjectId/.
Don't worry about this issue, it is not affecting functionality in any way.
