### ISSUE TITLE
Property 'MongoDB' does not exist on type 'Transports'

### ISSUE THREAD

**Issue by blove** [winstonjs/winston-mongodb#97]
I am running into an issue with the TypeScript definition file for this project. I have installed the `@types/winston` TypeScript declaration file using npm. I believe the issue is that the TypeScript declaration file `winston-mongodb.d.ts` does not extend the transports object.

Here is the code that I am using:

<pre><code>// logger
import { Logger, LoggerInstance, transports } from "winston";

// winston-mongodb log transport
import { MongoDB } from "winston-mongodb";
require("winston-mongodb").MongoDB;

// config logger
const logger = new (Logger)({
  transports: [
    new (transports.Console)({ level: "debug" }),
    new (transports.MongoDB)({
      collection: "logs",
      db: container.get<Configuration>(TYPES.Configuration).db.mongodb
    })
  ]
});</code></pre>

The error occurs on the line when I am configuring the transports: `Property 'MongoDB' does not exist on type 'Transports'`.

**Comment by blove** [comment]
It looks like executing `npm install @types/winston --save-dev` changed the formatting of package.json. I apologize if that is an issue, and would be happy to manually add the dependency if necessary.

**Comment by blove** [comment]
Sorry for the confusion, but this will not work given the way that the Transports interface is defined in winston's index.d.ts file. Using this updated declaration I was able to compile, but the import of the transports object from the winston module was not resolving correctly. Perhaps this is due to my lack of declaration merging in TS, but I think the winston index.d.ts file needs to export the interfaces so they can be merged by the compiler. You can disregard this PR, however, this is still an issue for TS users.

**Comment by yurijmikhalevich** [comment]
Merged. Thank you!

**Comment by yurijmikhalevich** [comment]
Released in version 3.0.0.

**Comment by sagar-gavhane** [comment]
Here is work around to this issue.

```js
const transports: any = winston.transports

const logger = winston.createLogger({
  format: winston.format.json(),
  transports: [
    new transports.MongoDB({
      level: "error",
      db: process.env.MONGODB_URI,
      collection: "logs",
    }),
  ],
})
```

**Comment by guna-yes** [comment]
var winston = require('winston');
const logInstance = createLogger({
 transports: [
                new winston.transports.MongoDB({
                    db: this.connectionURl,
                    collection: this.collection, 
                })
            ]
})

The above code solved the problem.
